##
#
source :rubygems

gem 'chef'
gem 'thin'
gem 'erubis'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-respond_to', :require => 'sinatra/respond_to'
gem 'sinatra-config-file', :require => 'sinatra/config_file'

group :development do
  gem 'rake'
  gem 'shotgun'
#  gem 'debugger'
end

group :test do
  gem 'rspec'
  gem 'rack-test', :require => 'rack/test'
#  gem 'debugger'
end
